CREATE DATABASE final_work;

use final_work;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `customers` (
  `CUSTOMER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(20) NOT NULL,
  `LASTNAME` VARCHAR(20) NOT NULL,
   `AGE` INT(10) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO customers(FIRSTNAME,LASTNAME,AGE) VALUES('Yakov', 'Badygin', 19);

CREATE TABLE `orders` (
	`ORDER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `CUSTOMER_ID` INT(10) UNSIGNED NOT NULL,
    `PRODUCT` nvarchar(255) not NULL,
    `PRICE` int(100) not NULL,
    PRIMARY KEY (`ORDER_ID`) USING BTREE,
    foreign key (`CUSTOMER_ID`) references customers(`CUSTOMER_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into orders(CUSTOMER_ID, PRODUCT, PRICE) values (1, 'Test', 150); 
